spring:
  datasource:
    url: jdbc:mysql://120.79.132.224:3306/shopkeeper?useSSL=false
    username: shopkeeper
    password: zju123
mybatis:
  type-aliases-package: cn.edu.zju.shopkeeper.domain
  config-location: classpath:mybatis.xml
server:
  port: 9090
  servlet:
    context-path: /shopkeeper
  tomcat:
    uri-encoding: UTF-8