spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xiangmushixun?useSSL=false
    username: root
    password: 123456
mybatis:
  type-aliases-package: cn.edu.zju.shopkeeper.domain
  config-location: classpath:mybatis.xml